version: '3.8'

services:
  arangodb:
    container_name: arangodb_clean_service_new
    image: arangodb:latest
    ports:
      - "8529:8529"
    environment:
      - ARANGO_ROOT_PASSWORD=mysecretpassword
    volumes:
      - arangodb-data:/var/lib/arangodb3
    networks:
      - app-network

    env_file:
      - ./backend/.env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - QUART_APP=app:app
      - ARANGO_HOST=http://arangodb_clean_service_new:8529
      - ARANGO_DB_NAME=renta_2024
      - ARANGO_USERNAME=root
      - ARANGO_PASSWORD=mysecretpassword
    networks:
      - app-network
    depends_on:
      - arangodb

    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"
    networks:
      - app-network
  
    env_file:
      - ./backend/.env

  tests:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: pytest -v --setup-show
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
      - QUART_APP=app:app
      - ARANGO_HOST=http://arangodb_clean_service_new:8529
      - ARANGO_DB_NAME=renta_2024
      - ARANGO_USERNAME=root
      - ARANGO_PASSWORD=mysecretpassword
    networks:
      - app-network
    depends_on:
      - arangodb
    env_file:
      - ./backend/.env

networks:
  app-network:
    driver: bridge

volumes:
  arangodb-data:
    driver: local
